### ISSUE TITLE
app crash on scroll down in a read-only old survey

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#1070]

**Comment by ifoche** [comment]
The error shown in crashlytics is this one:
```
Fatal Exception: java.lang.NullPointerException
       at org.eyeseetea.malariacare.layout.utils.AutoTabViewHolder.setRadioChecked(AutoTabViewHolder.java:140)
       at org.eyeseetea.malariacare.layout.adapters.survey.AutoTabAdapter.setValues(AutoTabAdapter.java:532)
       at org.eyeseetea.malariacare.layout.adapters.survey.AutoTabAdapter.getView(AutoTabAdapter.java:222)
       at android.widget.AbsListView.obtainView(AbsListView.java:2713)
       at android.widget.ListView.makeAndAddView(ListView.java:1811)
       at android.widget.ListView.fillDown(ListView.java:697)
       at android.widget.ListView.fillGap(ListView.java:661)
       at android.widget.AbsListView.trackMotionScroll(AbsListView.java:6689)
       at android.widget.AbsListView.scrollIfNeeded(AbsListView.java:3925)
       at android.widget.AbsListView.onTouchMove(AbsListView.java:4777)
       at android.widget.AbsListView.onTouchEvent(AbsListView.java:4605)
       at android.view.View.dispatchTouchEvent(View.java:8135)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2425)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2149)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2164)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2164)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2164)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2453)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2164)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2164)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2164)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2164)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2164)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2164)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2164)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2164)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2295)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1622)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2565)
       at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2243)
       at android.view.View.dispatchPointerEvent(View.java:8343)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4766)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4632)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4190)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4244)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4213)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4324)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4221)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4381)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4190)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4244)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4213)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4221)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4190)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6564)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6481)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6452)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6417)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6644)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:138)
       at android.os.Looper.loop(Looper.java:131)
       at android.app.ActivityThread.main(ActivityThread.java:5598)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by idelcano** [comment]
Info:
Some value-option relations did not converted in the pull.
I think it only happend with the surveys pushed before this  
[PR](https://github.com/EyeSeeTea/malariapp/pull/1051), and i think it is solved for the future surveys.
