### ISSUE TITLE
H14.1 bugs and enhace video preview

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#1073]

**Comment by ifoche** [comment]
Testing the apk in client device crashed the application immediately after the pull. The agreement about it was:
- [ ] Test the app from zero in a physical new device, and fix any crash using ifoche_test user
- [ ] Instead of a simple text link on videos, put a clickable png/jpeg image preview
- [ ] Upload at least 2 videos and see the performance with them (check what happens while the video is still not downloaded in the phone, and manage it properly)
- [ ] When possible, use the json google identification method to avoid user introducing his google account in the app (Optional)

**Comment by ivanarrizabalaga** [comment]
Given apk from scratch breaks with the given stacktrace:

```
06-13 17:00:50.886 21176-21176/? D/DriveRestController: Init drive credential
06-13 17:00:58.506 21176-21737/? D/DownloadMediaTask: Downloading resource: 0B8KIRhh6kcl6QTFHTW5oODE5ZVU ...
06-13 17:00:59.116 21176-21737/? E/DownloadMediaTask: downloadFile error: null
06-13 17:00:59.116 21176-21737/? D/DownloadMediaTask: Downloading resource: 0B8KIRhh6kcl6Sk5fQnZYeVo5cUk ...
06-13 17:00:59.136 21176-21737/? I/GoogleAuthUtil: Error on service connection.
                                                   java.lang.InterruptedException
                                                       at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1197)
                                                       at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:306)
                                                       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:407)
                                                       at com.google.android.gms.common.zza.zzoJ(Unknown Source)
                                                       at com.google.android.gms.auth.zzd.zza(Unknown Source)
                                                       at com.google.android.gms.auth.zzd.zzc(Unknown Source)
                                                       at com.google.android.gms.auth.zzd.getToken(Unknown Source)
                                                       at com.google.android.gms.auth.zzd.getToken(Unknown Source)
                                                       at com.google.android.gms.auth.zzd.getToken(Unknown Source)
                                                       at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
                                                       at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential.getToken(GoogleAccountCredential.java:255)
                                                       at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:279)
                                                       at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:859)
                                                       at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
                                                       at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
                                                       at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
                                                       at org.eyeseetea.malariacare.drive.DownloadMediaTask.downloadFile(DownloadMediaTask.java:95)
                                                       at org.eyeseetea.malariacare.drive.DownloadMediaTask.sync(DownloadMediaTask.java:72)
                                                       at org.eyeseetea.malariacare.drive.DownloadMediaTask.doInBackground(DownloadMediaTask.java:55)
                                                       at org.eyeseetea.malariacare.drive.DownloadMediaTask.doInBackground(DownloadMediaTask.java:26)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                       at java.lang.Thread.run(Thread.java:818)
06-13 17:00:59.736 21176-21737/? E/DownloadMediaTask: downloadFile error: null
06-13 17:00:59.746 21176-21737/? D/DownloadMediaTask: Downloading resource: 0B8KIRhh6kcl6QTFHTW5oODE5ZVU ...
06-13 17:00:59.826 21176-21176/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: org.eyeseetea.malariacare.hnqispull, PID: 21176
                                                   java.lang.NullPointerException: println needs a message
                                                       at android.util.Log.println_native(Native Method)
                                                       at android.util.Log.e(Log.java:334)
                                                       at org.eyeseetea.malariacare.drive.DownloadMediaTask.onCancelled(DownloadMediaTask.java:125)
                                                       at android.os.AsyncTask.onCancelled(AsyncTask.java:405)
                                                       at android.os.AsyncTask.finish(AsyncTask.java:630)
                                                       at android.os.AsyncTask.access$600(AsyncTask.java:177)
                                                       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:145)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5832)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
06-13 17:01:00.006 21176-21737/? E/DownloadMediaTask: downloadFile error: null
06-13 17:01:00.006 21176-21737/? D/DownloadMediaTask: Downloading resource: 0B8KIRhh6kcl6Sk5fQnZYeVo5cUk ...
06-13 17:01:00.016 21176-21737/? I/GoogleAuthUtil: Error on service connection.
                                                   java.lang.InterruptedException
                                                       at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1197)
                                                       at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:306)
                                                       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:407)
                                                       at com.google.android.gms.common.zza.zzoJ(Unknown Source)
                                                       at com.google.android.gms.auth.zzd.zza(Unknown Source)
                                                       at com.google.android.gms.auth.zzd.zzc(Unknown Source)
                                                       at com.google.android.gms.auth.zzd.getToken(Unknown Source)
                                                       at com.google.android.gms.auth.zzd.getToken(Unknown Source)
                                                       at com.google.android.gms.auth.zzd.getToken(Unknown Source)
                                                       at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
                                                       at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential.getToken(GoogleAccountCredential.java:255)
                                                       at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:279)
                                                       at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:859)
                                                       at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
                                                       at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
                                                       at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
                                                       at org.eyeseetea.malariacare.drive.DownloadMediaTask.downloadFile(DownloadMediaTask.java:95)
                                                       at org.eyeseetea.malariacare.drive.DownloadMediaTask.sync(DownloadMediaTask.java:72)
                                                       at org.eyeseetea.malariacare.drive.DownloadMediaTask.doInBackground(DownloadMediaTask.java:55)
                                                       at org.eyeseetea.malariacare.drive.DownloadMediaTask.doInBackground(DownloadMediaTask.java:26)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                       at java.lang.Thread.run(Thread.java:818)
06-13 17:01:00.726 21176-21737/? E/DownloadMediaTask: downloadFile error: null
```

**Comment by ifoche** [comment]
Can you test it again? I've just added a new OAuth and API key credential combination that I think we were missing

**Comment by ifoche** [comment]
The DE "KE HNQIS HIV-140-HTC-Explores support networks available" now contains the id "0B8KIRhh6kcl6SUhBdmVYT0ZhMjQ" in the video attribute, that corresponds to a .mov video. Please let me know if there's a problem with it

**Comment by ivanarrizabalaga** [comment]
Some notes:

 - Now the same apk works fine.
 - Downloading 2 videos, no problem, it went pretty fast:

```
06-13 17:35:04.571 6033-6590/? D/DownloadMediaTask: Downloading resource: 0B8KIRhh6kcl6QTFHTW5oODE5ZVU ...
06-13 17:35:05.591 6033-6590/? D/DownloadMediaTask: 	filename: cartoon-mosquito-9.png
06-13 17:35:06.251 6033-6590/? D/DownloadMediaTask: 	saved in /data/data/org.eyeseetea.malariacare.hnqispull/files/cartoon-mosquito-9.png
06-13 17:35:06.251 6033-6590/? D/DownloadMediaTask: Downloading resource: 0B8KIRhh6kcl6Sk5fQnZYeVo5cUk ...
06-13 17:35:06.571 6033-6590/? D/DownloadMediaTask: 	filename: MVA ENGLISH.mp4
06-13 17:35:18.241 6033-6590/? D/DownloadMediaTask: 	saved in /data/data/org.eyeseetea.malariacare.hnqispull/files/MVA ENGLISH.mp4
06-13 17:35:18.241 6033-6590/? D/DownloadMediaTask: Downloading resource: 0B8KIRhh6kcl6SUhBdmVYT0ZhMjQ ...
06-13 17:35:18.631 6033-6590/? D/DownloadMediaTask: 	filename: LARCs_FINAL_V3.mov
06-13 17:36:00.941 6033-6590/? D/DownloadMediaTask: 	saved in /data/data/org.eyeseetea.malariacare.hnqispull/files/LARCs_FINAL_V3.mov
```

 - Feedback list keeps working very smooth.
 - I'm checking againg about responsiveness with downloading

**Comment by ivanarrizabalaga** [comment]
mov files are not fully supported by android:

http://stackoverflow.com/questions/5482220/cant-play-mov-file-in-videoview

**Comment by ifoche** [comment]
ok, I've added another video with id=0B8KIRhh6kcl6UmNZbHB5YXliMG8 to DE "KE HNQIS HIV-150-HTC-Explains result interpretation" (corresponding a mp4 file). Can you...
1. show a little Toast saying "Invalid extension for file" or something like that, whenever it's not a proper video/image file
2. Try now that you have 2 videos just to check it's properly working
...?

**Comment by ivanarrizabalaga** [comment]
Some links related to anonymous hardcoded session:

http://stackoverflow.com/questions/28217089/google-drive-api-oauth2-0-how-to-automate-authentication-process-doubts-and

http://stackoverflow.com/questions/19766912/how-do-i-authorise-an-app-web-or-installed-without-user-intervention-canonic/19766913
