### ISSUE TITLE
Feedback composite score error

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/malariapp#1326]

**Comment by idelcano** [comment]
Error log:
  

> 
    D/.AlarmPushReceiverB&D: onReceive
    D/.AlarmPushReceiverB&D: onReceive asking for push
    D/.ConvertToSDKVisitorB&D: new convertToSdkVisitor
    D/.PushServiceStrategy: execute push
    D/.AlarmPushReceiverB&D: onReceive
    D/.AlarmPushReceiverB&D: onReceive asking for push
     D/.PushServiceStrategy: Starting push process...
     D/.CheckSurveysB&D: Quarantine size: 0
     D/.CheckSurveysB&D: Quarantine thread finished
     D/.PushControllerB&D: Network connected
     I/.AlarmPushReceiverB&D: isDoneFail
     E/.PushServiceStrategy: Pending surveys not found
     D/.PushServiceStrategy: execute push
     D/.PushServiceStrategy: Starting push process...
     D/.CheckSurveysB&D: Quarantine size: 0
     D/.CheckSurveysB&D: Quarantine thread finished
     D/.PushControllerB&D: Network connected
     I/.AlarmPushReceiverB&D: isDoneFail
     E/.PushServiceStrategy: Pending surveys not found
    D/.AlarmPushReceiverB&D: onReceive
    D/.AlarmPushReceiverB&D: onReceive asking for push
    D/.ConvertToSDKVisitorB&D: new convertToSdkVisitor
     D/.PushServiceStrategy: execute push
     D/.PushServiceStrategy: Starting push process...
     D/.CheckSurveysB&D: Quarantine size: 0
     D/.CheckSurveysB&D: Quarantine thread finished
     D/.PushControllerB&D: Network connected
     I/.AlarmPushReceiverB&D: isDoneFail
     E/.PushServiceStrategy: Pending surveys not found
    D/.ScoreRegister: getCompositeScore 0 -> [156.66, 251.0]
    I/art: Background sticky concurrent mark sweep GC freed 248076(10MB) AllocSpace objects, 6(96KB) LOS objects, 14% free, 46MB/54MB, paused 1.360ms total 150.983ms
    D/.SurveyService: getFeedbackItems: 529
    I/.Session: putServiceValue(org.eyeseetea.malariacare.services.SurveyService.PREPARE_FEEDBACK_ACTION_ITEMS, [org.eyeseetea.malariacare.data.database.utils.feedback.CompositeScoreFeedback@8b7011a1, org.eyeseetea.malariacare.data.database.utils.feedback.CompositeScoreFeedback@2e8a62a3, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@d38e2c99, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@17aa2a98, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@6d27d48e, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@e89167ee, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@8855aa1a, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@6f24ff0f, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@9df21e5f, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@f3744511, org.eyeseetea.malariacare.data.database.utils.feedback.CompositeScoreFeedback@15ab9ef0, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@248fe647, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@1e0e3bb7, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@db322603, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@58b180dc, org.eyeseetea.malariacare.data.database.utils.feedback.CompositeScoreFeedback@66fdfff7, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@9f8e79f3, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@586b1828, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@298891fe, org.eyeseetea.malariacare.data.database.utils.feedback.CompositeScoreFeedback@c01ec899, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@e2b870cf, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@13e260da, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@3786fe26, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@edb1e9fb, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@35aa9c78, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@8f1e5101, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@3be53948, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@78a4f9aa, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@c0fdf95d, org.eyeseetea.malariacare.data.database.utils.feedback.CompositeScoreFeedback@b616f7bc, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@19d5fba, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@c6a7d465, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@bfc748c1, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@22087cf, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@9bebce94, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@fa37a54f, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@ef0ebb05, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@19f60f97, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@f4a56e27, org.eyeseetea.malariacare.data.database.utils.feedback.CompositeScoreFeedback@d2033b9b, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@48e014f9, org.eyeseetea.malariacare.data.database.utils.feedback.CompositeScoreFeedback@d5a49247, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@755cd568, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@a23478a6, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@cded75b2, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@3021c407, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@78763bd8, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedb
    D/.SurveyService: reloadDashboard
    D/.SurveyService: getCompletedSurveys (Thread:3214)
    I/.Session: putServiceValue(org.eyeseetea.malariacare.services.SurveyService.ALL_COMPLETED_SURVEYS_ACTION, [])
    D/.SurveyService: getAllCreateSurveyData (Thread:3214)
    I/.Session: putServiceValue(org.eyeseetea.malariacare.services.SurveyService.ALL_CREATE_SURVEY_DATA_ACTION, org.eyeseetea.malariacare.data.database.utils.services.BaseServiceBundle@35cd7654)
    D/.SurveyService: getAllUncompletedUnsentUnplanedSurveys (Thread:3214)
    I/.Session: putServiceValue(org.eyeseetea.malariacare.services.SurveyService.ALL_IN_PROGRESS_SURVEYS_ACTION, [])
    D/.SurveyService: getAllMonitorData (Thread:3214)
    D/.FeedbackActivity: onReceive
    I/.Session: putServiceValue(org.eyeseetea.malariacare.services.SurveyService.ALL_MONITOR_DATA_ACTION, org.eyeseetea.malariacare.data.database.utils.services.BaseServiceBundle@1b8129fd)
    D/.SurveyService: getAllPrograms (Thread:3214)
    I/.Session: putServiceValue(org.eyeseetea.malariacare.services.SurveyService.ALL_PROGRAMS_ACTION, [Program{id=21, uid='ggxhuvMBtxj', name='KE HNQIS Cervical Cancer: Screening and Cryotherapy', stage_uid='IAC6i85iLZr'}, Program{id=22, uid='MHadckkbMut', name='KE HNQIS Family Planning', stage_uid='vochmk6s1iM'}, Program{id=23, uid='XRqyZbWDgWl', name='KE HNQIS HIV', stage_uid='CWXKyHQSbL2'}, Program{id=24, uid='u6pCofOY3O7', name='KE HNQIS Hypertension', stage_uid='iv2t5GZRVOc'}, Program{id=25, uid='Wps8E2P8P9S', name='KE HNQIS IMCI', stage_uid='Oii8KOmVXZN'}, Program{id=26, uid='Emzrjjdcfcq', name='KE HNQIS Maternal and Newborn Health', stage_uid='KyRVY0cWMj0'}, Program{id=27, uid='viBtnUfo7Wk', name='KE HNQIS Newborn Resuscitation', stage_uid='GzqmkoyZ5I9'}, Program{id=28, uid='SAuAGeeWGIW', name='KE HNQIS Tuberculosis', stage_uid='ElvViIshVCo'}, Program{id=29, uid='TPW9xYrV8i8', name='KE HNQIS Work Environment', stage_uid='wwf1OYeXWBf'}])
    D/.SurveyService: reloadPlanningSurveys
    E/SQLiteLog: (284) automatic index on OrgUnitProgramRelation(id_org_unit)
    I/.Session: putServiceValue(org.eyeseetea.malariacare.services.SurveyService.PLANNED_SURVEYS_ACTION, org.eyeseetea.malariacare.data.database.utils.services.PlannedServiceBundle@77826f2)
    I/.SurveyService: Active module: ImproveModuleController
    I/.ScoreRegister: Register tab score: TB Treatment Service Point
    I/.ScoreRegister: Register tab score: Gender Based Violence (GBV)
    I/.ScoreRegister: Register tab score: HIV Exposed Infants (HEI)
    I/.ScoreRegister: Register tab score: PMTCT Labor and Delivery
    I/.ScoreRegister: Register tab score: PMTCT-ANC & Postnatal
    I/.ScoreRegister: Register tab score: Care and Treatment
    I/.ScoreRegister: Register tab score: Point-of-Care Testing (POCT)
    I/.ScoreRegister: Register tab score: Laboratory
    I/.ScoreRegister: Register tab score: HTS/C&T Facility Management
    I/.ScoreRegister: Register tab score: HIV Testing Services (HTS)
    E/SQLiteLog: (284) automatic index on Question(id_composite_score)
    D/.DetailsFragment: onReceive
    D/.DetailsFragment: refreshScreen (Thread: 1): 0
    D/.MonitorFragment: onReceive
    D/.MonitorFragment: reloadSurveys (Thread: 1): 41
    D/.PlannedFragment: onReceive
    D/.PlannedFragment: Loading program: null
    D/.PlannedAdapter: applyFilter:Program{id=0, uid='null', name='ALL ASSESSMENTS', stage_uid='null'}
    D/.PlannedAdapter: updateNumShown
    D/.PlannedAdapter: updateNumShown:4
    I/Choreographer: Skipped 35 frames!  The application may be doing too much work on its main thread.
    D/AndroidRuntime: Shutting down VM
    E/AndroidRuntime: FATAL EXCEPTION: main
    Process: , PID: 8565
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
    at org.eyeseetea.malariacare.layout.score.ScoreRegister.getRecursiveScore(ScoreRegister.java:91)
    at org.eyeseetea.malariacare.layout.score.ScoreRegister.getCompositeScore(ScoreRegister.java:117)
    at org.eyeseetea.malariacare.data.database.utils.feedback.CompositeScoreFeedback.getScore(CompositeScoreFeedback.java:52)
    at org.eyeseetea.malariacare.layout.adapters.survey.FeedbackAdapter.getViewByCompositeScoreFeedback(FeedbackAdapter.java:156)
    at org.eyeseetea.malariacare.layout.adapters.survey.FeedbackAdapter.getView(FeedbackAdapter.java:128)
    at android.widget.AbsListView.obtainView(AbsListView.java:2823)
    at android.widget.ListView.makeAndAddView(ListView.java:1884)
    at android.widget.ListView.fillDown(ListView.java:713)
    at android.widget.ListView.fillFromTop(ListView.java:779)
    at android.widget.ListView.layoutChildren(ListView.java:1679)
    at android.widget.AbsListView.onLayout(AbsListView.java:2627)
    at android.view.View.layout(View.java:16695)
    at android.view.ViewGroup.layout(ViewGroup.java:5328)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
    at android.view.View.layout(View.java:16695)
    at android.view.ViewGroup.layout(ViewGroup.java:5328)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
    at android.view.View.layout(View.java:16695)
    at android.view.ViewGroup.layout(ViewGroup.java:5328)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
    at android.view.View.layout(View.java:16695)
    at android.view.ViewGroup.layout(ViewGroup.java:5328)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
    at android.view.View.layout(View.java:16695)
    at android.view.ViewGroup.layout(ViewGroup.java:5328)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
    at android.view.View.layout(View.java:16695)
    at android.view.ViewGroup.layout(ViewGroup.java:5328)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
    at android.view.View.layout(View.java:16695)
    at android.view.ViewGroup.layout(ViewGroup.java:5328)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
    at android.view.View.layout(View.java:16695)
    at android.view.ViewGroup.layout(ViewGroup.java:5328)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
    at android.view.View.layout(View.java:16695)
    at android.view.ViewGroup.layout(ViewGroup.java:5328)
    at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
    at android.view.View.layout(View.java:16695)
    at android.view.ViewGroup.layout(ViewGroup.java:5328)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
    at android.view.View.layout(View.java:16695)
    at android.view.ViewGroup.layout(ViewGroup.java:5328)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
    at android.view.View.layout(View.java:16695)
    at android.view.ViewGroup.layout(ViewGroup.java:5328)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
    at android.view.View.layout(View.java:16695)
    at android.view.ViewGrou




> I/System.out:(HTTPLog)-Static: isSBSettingEnabled false
I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
I/.ScoreRegister: Register composite score: 0
I/.ScoreRegister: Register composite score: 1
I/.ScoreRegister: Register composite score: 1.1
I/.ScoreRegister: Register composite score: 1.2
I/.ScoreRegister: Register composite score: 1.3
I/.ScoreRegister: Register composite score: 1.4
I/.ScoreRegister: Register composite score: 1.5
I/.ScoreRegister: Register composite score: 1.6
I/.ScoreRegister: Register composite score: 1.7
I/.ScoreRegister: Register composite score: 1.8
I/.ScoreRegister: Register composite score: 1.9
I/.ScoreRegister: Register composite score: 1.11
I/.ScoreRegister: Register composite score: 1.12
I/.ScoreRegister: Register composite score: 1.13
I/.ScoreRegister: Register composite score: 2
I/.ScoreRegister: Register composite score: 2.1
I/.ScoreRegister: Register composite score: 2.2
I/.ScoreRegister: Register composite score: 2.3
I/.ScoreRegister: Register composite score: 2.4
I/.ScoreRegister: Register composite score: 2.5
I/.ScoreRegister: Register composite score: 2.6
I/.ScoreRegister: Register composite score: 2.7
I/.ScoreRegister: Register composite score: 2.8
I/.ScoreRegister: Register composite score: 2.9
I/.ScoreRegister: Register composite score: 3
I/.ScoreRegister: Register composite score: 3.1
I/.ScoreRegister: Register composite score: 3.2
I/.ScoreRegister: Register composite score: 3.3
I/.ScoreRegister: Register composite score: 3.4
I/.ScoreRegister: Register composite score: 3.5
I/.ScoreRegister: Register composite score: 3.6
I/.ScoreRegister: Register composite score: 4
I/.ScoreRegister: Register composite score: 4.1
I/.ScoreRegister: Register composite score: 4.2
I/.ScoreRegister: Register composite score: 4.3
I/.ScoreRegister: Register composite score: 4.4
I/.ScoreRegister: Register composite score: 5
I/.ScoreRegister: Register composite score: 5.1
I/.ScoreRegister: Register composite score: 5.3
I/.ScoreRegister: Register composite score: 5.4
I/.ScoreRegister: Register composite score: 5.5
I/.ScoreRegister: Register composite score: 5.6
I/.ScoreRegister: Register composite score: 5.7
I/.ScoreRegister: Register composite score: 5.8
I/.ScoreRegister: Register composite score: 5.9
I/.ScoreRegister: Register composite score: 5.11
I/.ScoreRegister: Register composite score: 5.12
I/.ScoreRegister: Register composite score: 5.13
I/.ScoreRegister: Register composite score: 5.14
I/.ScoreRegister: Register composite score: 5.15
I/.ScoreRegister: Register composite score: 5.16
I/.ScoreRegister: Register composite score: 5.2
I/.ScoreRegister: Register composite score: 5.18
I/.ScoreRegister: Register composite score: 6
I/.ScoreRegister: Register composite score: 6.1
I/.ScoreRegister: Register composite score: 6.2
I/.ScoreRegister: Register composite score: 6.3
I/.ScoreRegister: Register composite score: 6.4
I/.ScoreRegister: Register composite score: 7
I/.ScoreRegister: Register composite score: 7.1
I/.ScoreRegister: Register composite score: 7.2
I/.ScoreRegister: Register composite score: 7.3
I/.ScoreRegister: Register composite score: 7.4
I/.ScoreRegister: Register composite score: 8
I/.ScoreRegister: Register composite score: 8.1
I/.ScoreRegister: Register composite score: 8.2
I/.ScoreRegister: Register composite score: 8.3
I/.ScoreRegister: Register composite score: 8.4
I/.ScoreRegister: Register composite score: 8.5
I/.ScoreRegister: Register composite score: 8.6
I/.ScoreRegister: Register composite score: 8.7
I/.ScoreRegister: Register composite score: 9
I/.ScoreRegister: Register composite score: 9.1
I/.ScoreRegister: Register composite score: 9.2
I/.ScoreRegister: Register composite score: 10
I/.ScoreRegister: Register composite score: 10.1
I/.ScoreRegister: Register composite score: 10.2
I/.ScoreRegister: Register composite score: 10.3
I/.ScoreRegister: Register composite score: 10.4
I/CrashlyticsCore: Crashlytics report upload complete: 58AEC6610102-0001-2175-BC5EAF7AE8C5.cls
W/art: Suspending all threads took: 13.531ms
I/art: Background partial concurrent mark sweep GC freed 289495(11MB) AllocSpace objects, 1(64KB) LOS objects, 27% free, 43MB/59MB, paused 1.234ms total 112.281ms
D/.ScoreRegister: getCompositeScore 0 -> [156.66, 251.0]
I/art: Background sticky concurrent mark sweep GC freed 125255(5MB) AllocSpace objects, 0(0B) LOS objects, 9% free, 51MB/56MB, paused 1.299ms total 100.535ms
D/.SurveyService: getFeedbackItems: 529
I/.Session: putServiceValue(org.eyeseetea.malariacare.services.SurveyService.PREPARE_FEEDBACK_ACTION_ITEMS, [org.eyeseetea.malariacare.data.database.utils.feedback.CompositeScoreFeedback@8b7011a1, org.eyeseetea.malariacare.data.database.utils.feedback.CompositeScoreFeedback@2e8a62a3, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@d38e2c99, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@17aa2a98, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@6d27d48e, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@e89167ee, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@8855aa1a, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@6f24ff0f, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@9df21e5f, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@f3744511, org.eyeseetea.malariacare.data.database.utils.feedback.CompositeScoreFeedback@15ab9ef0, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@248fe647, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@1e0e3bb7, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@db322603, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@58b180dc, org.eyeseetea.malariacare.data.database.utils.feedback.CompositeScoreFeedback@66fdfff7, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@9f8e79f3, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@586b1828, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@298891fe, org.eyeseetea.malariacare.data.database.utils.feedback.CompositeScoreFeedback@c01ec899, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@e2b870cf, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@13e260da, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@3786fe26, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@edb1e9fb, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@35aa9c78, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@8f1e5101, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@3be53948, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@78a4f9aa, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@c0fdf95d, org.eyeseetea.malariacare.data.database.utils.feedback.CompositeScoreFeedback@b616f7bc, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@19d5fba, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@c6a7d465, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@bfc748c1, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@22087cf, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@9bebce94, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@fa37a54f, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@ef0ebb05, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@19f60f97, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@f4a56e27, org.eyeseetea.malariacare.data.database.utils.feedback.CompositeScoreFeedback@d2033b9b, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@48e014f9, org.eyeseetea.malariacare.data.database.utils.feedback.CompositeScoreFeedback@d5a49247, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@755cd568, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@a23478a6, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@cded75b2, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@3021c407, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedback@78763bd8, org.eyeseetea.malariacare.data.database.utils.feedback.QuestionFeedb
I/art: Background partial concurrent mark sweep GC freed 295903(12MB) AllocSpace objects, 10(729KB) LOS objects, 26% free, 43MB/59MB, paused 1.762ms total 131.247ms
