### ISSUE TITLE
On quarantine getEvents() network interruption crash

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/malariapp#1398]
I did two times the interruption of the getEvents method. I created and breakpoint in return client.newCall (request) .execute (); and discconect the movile on this point.
The getEvents method is a loop of orgUnits and programs.
I allow it the first getEvents, and disconect the next time.

The sdk carsh with an exception saving some event.
Three surveys were set to Sending and never recovery.

Log:

04-18 17:58:32.618 8685-16743/org.eyeseetea.malariacare.eds_bb D/.CheckSurveysB&D: Quarantine size: 1
04-18 17:58:32.619 8685-17243/org.eyeseetea.malariacare.eds_bb D/TrackerDataSender: got this many events to send:2
04-18 17:58:32.629 8685-17243/org.eyeseetea.malariacare.eds_bb D/Retrofit: ---> HTTP POST https://eds-dev.psi-mis.org/api/events/
04-18 17:58:32.630 8685-17243/org.eyeseetea.malariacare.eds_bb D/RepoManager: Request{method=POST, url=https://eds-dev.psi-mis.org/api/events/, tag=Request{method=POST, url=https://eds-dev.psi-mis.org/api/events/, tag=null}}
04-18 17:58:32.648 8685-16743/org.eyeseetea.malariacare.eds_bb D/.CheckSurveysB&D: /api/events.json?orgUnit=rn0Ph9hf1p3&startDate=2017-04-17&endDate=2017-04-27&skipPaging=true&fields=event,orgUnit,program,dataValues
04-18 17:58:34.902 8685-16743/org.eyeseetea.malariacare.eds_bb D/.CheckSurveysB&D: Set quarantine survey as completed37 date 2017-04-18T17:49:20.784+0200
04-18 17:58:34.914 8685-16743/org.eyeseetea.malariacare.eds_bb D/.CheckSurveysB&D: Quarantine thread finished
04-18 17:58:34.915 8685-16743/org.eyeseetea.malariacare.eds_bb D/.PushController: Starting PUSH process...
04-18 17:58:34.915 8685-16743/org.eyeseetea.malariacare.eds_bb W/System.err: java.lang.IllegalArgumentException: Object already registered.
04-18 17:58:34.916 8685-16743/org.eyeseetea.malariacare.eds_bb W/System.err:     at com.squareup.otto.Bus.register(Bus.java:223)
04-18 17:58:34.916 8685-16743/org.eyeseetea.malariacare.eds_bb W/System.err:     at org.eyeseetea.malariacare.database.iomodules.dhis.exporter.PushController.register(PushController.java:73)
04-18 17:58:34.916 8685-16743/org.eyeseetea.malariacare.eds_bb W/System.err:     at org.eyeseetea.malariacare.database.iomodules.dhis.exporter.PushController.push(PushController.java:119)
04-18 17:58:34.916 8685-16743/org.eyeseetea.malariacare.eds_bb W/System.err:     at org.eyeseetea.malariacare.network.PushClient.pushSDK(PushClient.java:79)
04-18 17:58:34.916 8685-16743/org.eyeseetea.malariacare.eds_bb W/System.err:     at org.eyeseetea.malariacare.services.PushService.pushAllPendingSurveys(PushService.java:113)
04-18 17:58:34.916 8685-16743/org.eyeseetea.malariacare.eds_bb W/System.err:     at org.eyeseetea.malariacare.services.PushService.onHandleIntent(PushService.java:83)
04-18 17:58:34.916 8685-16743/org.eyeseetea.malariacare.eds_bb W/System.err:     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
04-18 17:58:34.916 8685-16743/org.eyeseetea.malariacare.eds_bb W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
04-18 17:58:34.916 8685-16743/org.eyeseetea.malariacare.eds_bb W/System.err:     at android.os.Looper.loop(Looper.java:154)
04-18 17:58:34.916 8685-16743/org.eyeseetea.malariacare.eds_bb W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
04-18 17:58:34.918 8685-16743/org.eyeseetea.malariacare.eds_bb D/.PushController: Preparing survey for pushing...
04-18 17:58:34.928 8685-16743/org.eyeseetea.malariacare.eds_bb D/.PopulateDB: Delete sdk db
04-18 17:58:34.928 8685-16743/org.eyeseetea.malariacare.eds_bb D/.PushController: Converting APP survey into a SDK event
04-18 17:58:34.933 8685-16743/org.eyeseetea.malariacare.eds_bb D/.ServerMetadata: WARNING: Control DE with code _OverallProductivity not found, ignoring
04-18 17:58:34.935 8685-16743/org.eyeseetea.malariacare.eds_bb D/.ServerMetadata: WARNING: Control DE with code _NextAssessmentDate not found, ignoring
04-18 17:58:34.944 8685-16743/org.eyeseetea.malariacare.eds_bb D/.ConvertToSDKVisitor: Creating event for survey (37) ...
04-18 17:58:34.945 8685-16743/org.eyeseetea.malariacare.eds_bb D/.ConvertToSDKVisitor: Creating event for survey (Survey{id_survey=37, id_program=5, id_org_unit=3, id_user=1, creation_date=Tue Apr 18 17:49:20 GMT+02:00 2017, completion_date=Tue Apr 18 17:51:41 GMT+02:00 2017, upload_date=Tue Apr 18 17:58:34 GMT+02:00 2017, scheduled_date=Wed Oct 18 17:35:31 GMT+02:00 2017, status=6, eventuid=t2RJfx9n8Xk}) ...
04-18 17:58:34.947 8685-16743/org.eyeseetea.malariacare.eds_bb D/.ConvertToSDKVisitor: Saving event rkGga792ISj
04-18 17:58:34.957 8685-16743/org.eyeseetea.malariacare.eds_bb D/.ConvertToSDKVisitor: Registering scores...
04-18 17:58:34.958 8685-16743/org.eyeseetea.malariacare.eds_bb I/.ScoreRegister: Register tab score: Data Management
04-18 17:58:34.958 8685-16743/org.eyeseetea.malariacare.eds_bb I/.ScoreRegister: Register tab score: Malaria Data Verification
04-18 17:58:34.958 8685-16743/org.eyeseetea.malariacare.eds_bb I/.ScoreRegister: Register tab score

**Comment by idelcano** [comment]
This is solved in #1402
