### ISSUE TITLE
App crash when toggle first parent question on Material and Newborn Health program

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/malariapp#1440]
In the server old-staging.psi-mis.org

04-20 16:07:22.835 32210-32210/org.eyeseetea.malariacare.hnqis_ng_bb E/SQLiteLog: (284) automatic index on QuestionOption(id_option_fk)
04-20 16:07:22.845 32210-32210/org.eyeseetea.malariacare.hnqis_ng_bb D/AndroidRuntime: Shutting down VM
04-20 16:07:22.965 32210-32210/org.eyeseetea.malariacare.hnqis_ng_bb E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                       Process: org.eyeseetea.malariacare.hnqis_ng_bb, PID: 32210
                                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'org.eyeseetea.malariacare.data.database.model.Tab org.eyeseetea.malariacare.data.database.model.Header.getTab()' on a null object reference
                                                                                           at org.eyeseetea.malariacare.layout.score.ScoreRegister.getNumDenum(ScoreRegister.java:109)
                                                                                           at org.eyeseetea.malariacare.layout.utils.AutoTabInVisibilityState.recursiveToggleChildrenVisibility(AutoTabInVisibilityState.java:181)
                                                                                           at org.eyeseetea.malariacare.layout.utils.AutoTabInVisibilityState.toggleChildrenVisibility(AutoTabInVisibilityState.java:156)
                                                                                           at org.eyeseetea.malariacare.layout.utils.AutoTabSelectedItem.toggleChildrenVisibility(AutoTabSelectedItem.java:94)
                                                                                           at org.eyeseetea.malariacare.layout.utils.AutoTabLayoutUtils.saveAndExpandChildren(AutoTabLayoutUtils.java:419)
                                                                                           at org.eyeseetea.malariacare.layout.utils.AutoTabLayoutUtils.itemSelected(AutoTabLayoutUtils.java:332)
                                                                                           at org.eyeseetea.malariacare.layout.adapters.survey.AutoTabAdapter$RadioGroupListener.onCheckedChanged(AutoTabAdapter.java:709)
                                                                                           at android.widget.RadioGroup.setCheckedId(RadioGroup.java:174)
                                                                                           at android.widget.RadioGroup.access$600(RadioGroup.java:54)
                                                                                           at android.widget.RadioGroup$CheckedStateTracker.onCheckedChanged(RadioGroup.java:358)
                                                                                           at android.widget.CompoundButton.setChecked(CompoundButton.java:164)
                                                                                           at org.eyeseetea.malariacare.views.CustomRadioButton.toggle(CustomRadioButton.java:243)
                                                                                           at android.widget.CompoundButton.performClick(CompoundButton.java:127)
                                                                                           at android.view.View$PerformClick.run(View.java:20910)
                                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                           at android.os.Looper.loop(Looper.java:145)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5951)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by idelcano** [comment]
The reason is in the server configuration, [this](https://old-staging.psi-mis.org/api/dataElements/s1OX8TgzRHg) question doesn't have header.
