### ISSUE TITLE
Create architecture to pull metadata from DHIS2

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#32]
An option should be created in the admin section (probably the ActionBar settings) called "Update from DHIS". This option calls DHIS and retrieve the changes in automatic questions from it.

**Comment by josemp10** [comment]
Yes, I agree. Anyway this is not going to be ready till the end of April (I guess). Should we remove this issue from the next release?

**Comment by adrianq** [comment]
Move it back to backlog and remove release tag!

**Comment by ifoche** [comment]
In principle, this task will be developed mainly by @josemp10 but, different things could be accomplished by @ifoche too, so group in charge will be @EyeSeeTea/josenacho, but I assign the issue to @josemp10

**Comment by adrianq** [comment]
This issue and some others are set to Milestone 7  and assigned to @josemp10. Are all these issues @josemp10 gonna be ready for Wednesday? If this is not the case can you move them back to backlog and set an appropriate release, please.

**Comment by adrianq** [comment]
Assigning this to @ifoche as  it has to do with the integration with DHIS SDK

**Comment by adrianq** [comment]
Subtask discussed yesterday:
   - [ ] Prototype integration
   - [ ] Test pull
   - [ ] Check  integration of other component

@ifoche please update and define a bit more in details the subtask as you get a better understanding of the task itself.

**Comment by ifoche** [comment]
the git submodule is completely integrated and the sdk commit selected in the git submodule (the DHIS-SDK repo) is 1c9cafd74e4dcc823fe659a01e012539ded9b42f. 

Now the git clone command need to be done like... 
git clone -b sdk_integration --recursive https://github.com/EyeSeeTea/malariapp.git

The definitive command will obviously be
git clone --recursive https://github.com/EyeSeeTea/malariapp.git

...whenever the branch will be merged to development and this one, to master.

I've verified that the app event capture properly works with that commit. With this, I can say that there is a "prototype integration". In this state both modules (our app and sdk) are aside, not using at all anything from the other, but now I think there are at least some steps that need to be done to consider this task as done:
- [ ] The pull capability (leaving the information there, without using that DB, but just to be able to take a look to the resulting DB and better understand it.
- [ ] Some UI components. A few work is needed to find out which components from the SDK UI part we can reuse, and try to use them if possible.
- [ ] Study the possibility of moving from Sugar to  DBFlow to use the same ORM that the SDK (just if it has better performance or more features)
- [ ] The interchange layer to do the whole pull

**Comment by josemp10** [comment]
Terrific work @ifoche.  This is really great! Do not hesitate to contact me for any questions related to the database. The data model that we have in lucid chart, is a simplication (less tables, less fields...) of the real one. So, let me know if you any questions on that regard

**Comment by ifoche** [comment]
Thanks @josemp10 . Yes I will need to ask you a few things related to DHIS users table, as I've decided to start by retrieving that data on our app start from DHIS server. Would you have a moment this weekend for that? Today I think I wont have enough things to ask you, but tomorrow probably yes...

**Comment by josemp10** [comment]
No problem. What about saturday morning?  I will probably be out after 13

**Comment by ifoche** [comment]
You mean tomorrow? For me is ok, better in the afternoon if you can

**Comment by josemp10** [comment]
Yes, Saturday.  I can make it till 13 of London (not sure after that). Afternoon definition is after 12...

**Comment by ifoche** [comment]
Now using login screen from sdk...but not yet able to manage the success :)

**Comment by ifoche** [comment]
when login is successful, app is accessed using dashboardDetailsActivity, but no user set in Session, and no logout managed. We need to better understand the way sdk is using the persistence in preferences

**Comment by ifoche** [comment]
Now login is working but a bug appears and the app crashes, so you need to enter the app twice. Logout works perfectly. The bug is:
07-04 10:03:47.471    2068-2068/org.eyeseetea.malariacare E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.eyeseetea.malariacare, PID: 2068
    java.lang.RuntimeException: Could not dispatch event: class org.hisp.dhis.android.sdk.events.ResponseEvent to handler [EventHandler public void org.eyeseetea.malariacare.LoginActivity.onReceiveResponse(org.hisp.dhis.android.sdk.events.ResponseEvent)]: Context cannot be null for FlowManager
            at com.squareup.otto.Bus.throwRuntimeException(Bus.java:458)
            at com.squareup.otto.Bus.dispatch(Bus.java:388)
            at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:369)
            at com.squareup.otto.Bus.post(Bus.java:338)
            at org.hisp.dhis.android.sdk.utils.MainThreadBus.access$001(MainThreadBus.java:41)
            at org.hisp.dhis.android.sdk.utils.MainThreadBus$1.run(MainThreadBus.java:56)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.IllegalStateException: Context cannot be null for FlowManager
            at com.raizlabs.android.dbflow.config.FlowManager.getContext(FlowManager.java:142)
            at com.raizlabs.android.dbflow.config.FlowSQLiteOpenHelper.<init>(FlowSQLiteOpenHelper.java:51)
            at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.createHelper(BaseDatabaseDefinition.java:161)
            at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getHelper(BaseDatabaseDefinition.java:155)
            at com.raizlabs.android.dbflow.config.BaseDatabaseDefinition.getWritableDatabase(BaseDatabaseDefinition.java:165)
            at com.raizlabs.android.dbflow.sql.SqlUtils.hasData(SqlUtils.java:208)
            at com.raizlabs.android.dbflow.sql.language.Where.hasData(Where.java:368)
            at org.hisp.dhis.android.sdk.persistence.models.User$Adapter.exists(User$Adapter.java:142)
            at org.hisp.dhis.android.sdk.persistence.models.User$Adapter.exists(User$Adapter.java:12)
            at com.raizlabs.android.dbflow.sql.SqlUtils.save(SqlUtils.java:227)
            at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:54)
            at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:54)
            at org.eyeseetea.malariacare.LoginActivity.onReceiveResponse(LoginActivity.java:169)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
            at com.squareup.otto.Bus.dispatch(Bus.java:386)
            at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:369)
            at com.squareup.otto.Bus.post(Bus.java:338)
            at org.hisp.dhis.android.sdk.utils.MainThreadBus.access$001(MainThreadBus.java:41)
            at org.hisp.dhis.android.sdk.utils.MainThreadBus$1.run(MainThreadBus.java:56)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by ifoche** [comment]
Bug solved (See #248)

**Comment by ifoche** [comment]
this issue is stopped until new pull time scheduling is accepted by PSI/Knowming

**Comment by ifoche** [comment]
dummy data and conversion are drafted in [this lines](https://github.com/EyeSeeTea/malariapp/blob/visitors_try/app/src/main/java/org/eyeseetea/malariacare/EyeSeeTeaApplication.java#L77-98). To complete this task, we would need to change dummyData() for the instructions to call SDK pull and move convertFromSDK() to:
 - the moment the user does his first login
 - when the user orders it by an specific action
