### ISSUE TITLE
App is crashing sometimes

### ISSUE THREAD

**Issue by josemp10** [EyeSeeTea/malariapp#369]
It seems that happens (sometimes, not always), if the user clicks on a Checkbox of a question with hide/show logic when the cursor is focused on a alphanumeric question

**Comment by josemp10** [comment]
It happens for example in the General OTSS tab:

1- Select the General OTSS tab
2- Put the cursor under one alpha-numeric response under the 'Health Facility Information' header
3- Check 'yes' for either the first or second question with a hidden response: 'Are there OPD staff formally trained in RDTs in the last two years?' or 'Are there OPD staff trained in ...' 
The application should crash 

However following  1, 2, 3, in other tabs doesn't make the app to crash.

**Comment by josemp10** [comment]
I couldn't replicate this bug on the emulator (it seems that only is happening on a real device). 

This is what I am getting using crashlytics (not very helpful I guess):

java.lang.IllegalArgumentException: parameter must be a descendant of this view
       at android.view.ViewGroup.offsetRectBetweenParentAndChild(ViewGroup.java:4770)
       at android.view.ViewGroup.offsetDescendantRectToMyCoords(ViewGroup.java:4707)
       at android.view.ViewRootImpl.scrollToRectOrFocus(ViewRootImpl.java:3145)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2701)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2644)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1255)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6625)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:812)
       at android.view.Choreographer.doCallbacks(Choreographer.java:612)
       at android.view.Choreographer.doFrame(Choreographer.java:582)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:798)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by ifoche** [comment]
it was solved by removing the focus and hidding the keyboard when scroll is activated
