### ISSUE TITLE
Poor DBFLow performance

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/malariapp#400]
Our domains are not using the lazy feature that was the main reason for changing from Sugar to DBFLow:

 - Turn any fk property into a ForeignKeyContainer + **toModel()**
 - Turn any list of childrens into a 'singleton' query

IMHO this should a high priority issue.

PD: You can log the queries that are being run  adding the line **com.raizlabs.android.dbflow.config.FlowLog.setMinimumLoggingLevel(FlowLog.Level.V)** in the code

**Comment by ifoche** [comment]
this may affect to #270 (check it)

**Comment by ifoche** [comment]
sorry for interrupting your work in this task, can you move to #470? thank you really

**Comment by ivanarrizabalaga** [comment]
Ok no problem

**Comment by ivanarrizabalaga** [comment]
To review:
```java
     Caused by: com.raizlabs.android.dbflow.structure.container.ForeignKeyContainer$InvalidMethodCallException: Cannot call save() on a foreign key container. Call load() instead
            at com.raizlabs.android.dbflow.structure.container.ForeignKeyContainer.save(ForeignKeyContainer.java:79)
            at org.eyeseetea.malariacare.database.model.Survey$Adapter.bindToStatement(Survey$Adapter.java:33)
            at org.eyeseetea.malariacare.database.model.Survey$Adapter.bindToStatement(Survey$Adapter.java:12)
            at com.raizlabs.android.dbflow.sql.SqlUtils.insert(SqlUtils.java:313)
            at com.raizlabs.android.dbflow.sql.SqlUtils.save(SqlUtils.java:268)
            at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:54)
            at org.eyeseetea.malariacare.database.model.Survey$Adapter.save(Survey$Adapter.java:294)
            at org.eyeseetea.malariacare.database.model.Survey$Adapter.save(Survey$Adapter.java:12)
            at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:50)
            at org.eyeseetea.malariacare.CreateSurveyActivity.createSurvey(CreateSurveyActivity.java:208)
```

**Comment by ivanarrizabalaga** [comment]
Couldnt manage to make it work.

I've created a sample demo from scratch according to the docs and it is not working as expected, :(.

There is a way left to explore but I dont want to consume more hours on this issue at this point.

**Comment by ivanarrizabalaga** [comment]
Some links:

https://github.com/Raizlabs/DBFlow/issues/396
https://github.com/Raizlabs/DBFlow/issues/328

**Comment by ifoche** [comment]
Look at DbOperation in SDK, to implement it

**Comment by ifoche** [comment]
@ivanarrizabalaga. Please check out the SDK in order to know how are they implementing it and let's try to give this task its last opportunity
