### ISSUE TITLE
Crash in API16 - the application crash when you click in compositeScores/scores or feedback

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/malariapp#599]
The log is:

11-25 11:30:01.563 1540-1540/? E/AndroidRuntime: FATAL EXCEPTION: main
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime: java.lang.NullPointerException
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.widget.AbsListView.obtainView(AbsListView.java:2269)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.widget.ListView.makeAndAddView(ListView.java:1769)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.widget.ListView.fillDown(ListView.java:672)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.widget.ListView.fillFromTop(ListView.java:733)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.widget.ListView.layoutChildren(ListView.java:1622)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.widget.AbsListView.onLayout(AbsListView.java:2102)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.View.layout(View.java:13754)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:4362)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.View.layout(View.java:13754)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:4362)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.View.layout(View.java:13754)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:4362)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.View.layout(View.java:13754)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:4362)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.View.layout(View.java:13754)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:4362)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:493)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.View.layout(View.java:13754)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:4362)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.View.layout(View.java:13754)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:4362)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.View.layout(View.java:13754)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:4362)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.View.layout(View.java:13754)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:4362)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1866)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1687)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:998)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4212)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:555)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:525)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:615)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:92)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4745)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
11-25 11:30:01.563 1540-1540/? E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

**Comment by idelcano** [comment]
Example:
If you are creating a survey, and select ICM checklist, if you select Composite Scores or Feedback the application crash.
In api17+ dont crash.

**Comment by idelcano** [comment]
I can´t reproduce the problem after do new pull..

**Comment by idelcano** [comment]
@ivanarrizabalaga Do not start this card. I will close it.
