### ISSUE TITLE
Check pull on physical device

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/malariapp#624]

**Comment by ivanarrizabalaga** [comment]
```log
12-04 16:38:52.759 11678-11814/org.eyeseetea.malariacare.hnqispull E/art: Throwing OutOfMemoryError "Failed to allocate a 32 byte allocation with 0 free bytes and 3GB until OOM"
12-04 16:38:52.969 11678-11690/org.eyeseetea.malariacare.hnqispull E/art: Throwing OutOfMemoryError "Failed to allocate a 36 byte allocation with 0 free bytes and 3GB until OOM"
12-04 16:38:53.179 11678-11685/org.eyeseetea.malariacare.hnqispull E/art: Throwing OutOfMemoryError "Failed to allocate a 52 byte allocation with 0 free bytes and 3GB until OOM"
12-04 16:38:54.519 11678-11690/org.eyeseetea.malariacare.hnqispull E/art: Throwing OutOfMemoryError "Failed to allocate a 28 byte allocation with 0 free bytes and 3GB until OOM" (recursive case)
12-04 16:38:54.529 11678-11690/org.eyeseetea.malariacare.hnqispull E/art: "FinalizerDaemon" daemon prio=5 tid=8 Runnable
12-04 16:38:54.529 11678-11690/org.eyeseetea.malariacare.hnqispull E/art:   | group="system" sCount=0 dsCount=0 obj=0x12c3a0e0 self=0xaf210800
12-04 16:38:54.529 11678-11690/org.eyeseetea.malariacare.hnqispull E/art:   | sysTid=11690 nice=0 cgrp=apps sched=0/0 handle=0xaf225300
12-04 16:38:54.529 11678-11690/org.eyeseetea.malariacare.hnqispull E/art:   | state=R schedstat=( 1890518580 135522721 873 ) utm=182 stm=7 core=3 HZ=100
12-04 16:38:54.529 11678-11690/org.eyeseetea.malariacare.hnqispull E/art:   | stack=0xb3fc3000-0xb3fc5000 stackSize=1036KB
12-04 16:38:54.529 11678-11690/org.eyeseetea.malariacare.hnqispull E/art:   | held mutexes= "mutator lock"(shared held)
12-04 16:38:54.529 11678-11690/org.eyeseetea.malariacare.hnqispull E/art:     at java.lang.ref.FinalizerReference.add(FinalizerReference.java:54)
12-04 16:38:54.529 11678-11690/org.eyeseetea.malariacare.hnqispull E/art:     at com.android.internal.os.BinderInternal$GcWatcher.finalize(BinderInternal.java:51)
12-04 16:38:54.529 11678-11690/org.eyeseetea.malariacare.hnqispull E/art:     at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:190)
12-04 16:38:54.529 11678-11690/org.eyeseetea.malariacare.hnqispull E/art:     at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:173)
12-04 16:38:54.529 11678-11690/org.eyeseetea.malariacare.hnqispull E/art:     at java.lang.Thread.run(Thread.java:818)
12-04 16:38:55.739 11678-11685/org.eyeseetea.malariacare.hnqispull E/art: Throwing OutOfMemoryError "Failed to allocate a 162 byte allocation with 44 free bytes and 44B until OOM" (recursive case)
12-04 16:38:55.749 11678-11685/org.eyeseetea.malariacare.hnqispull E/art: "JDWP" daemon prio=5 tid=3 Runnable
12-04 16:38:55.749 11678-11685/org.eyeseetea.malariacare.hnqispull E/art:   | group="system" sCount=0 dsCount=0 obj=0x12c35080 self=0xaf40e400
12-04 16:38:55.749 11678-11685/org.eyeseetea.malariacare.hnqispull E/art:   | sysTid=11685 nice=0 cgrp=apps sched=0/0 handle=0xafc55180
12-04 16:38:55.749 11678-11685/org.eyeseetea.malariacare.hnqispull E/art:   | state=R schedstat=( 4200183457 731225868 2173 ) utm=409 stm=11 core=0 HZ=100
12-04 16:38:55.749 11678-11685/org.eyeseetea.malariacare.hnqispull E/art:   | stack=0xb45e7000-0xb45e9000 stackSize=1012KB
12-04 16:38:55.749 11678-11685/org.eyeseetea.malariacare.hnqispull E/art:   | held mutexes= "mutator lock"(shared held)
12-04 16:38:55.749 11678-11685/org.eyeseetea.malariacare.hnqispull E/art:     at java.nio.ByteBuffer.wrap(ByteBuffer.java:113)
12-04 16:38:55.749 11678-11685/org.eyeseetea.malariacare.hnqispull E/art:     at org.apache.harmony.dalvik.ddmc.ChunkHandler.wrapChunk(ChunkHandler.java:80)
12-04 16:38:55.749 11678-11685/org.eyeseetea.malariacare.hnqispull E/art:     at android.ddm.DdmHandleHeap.handleHPIF(DdmHandleHeap.java:112)
12-04 16:38:55.749 11678-11685/org.eyeseetea.malariacare.hnqispull E/art:     at android.ddm.DdmHandleHeap.handleChunk(DdmHandleHeap.java:85)
12-04 16:38:55.749 11678-11685/org.eyeseetea.malariacare.hnqispull E/art:     at org.apache.harmony.dalvik.ddmc.DdmServer.dispatch(DdmServer.java:171)
12-04 16:38:56.689 11678-11814/org.eyeseetea.malariacare.hnqispull E/art: Throwing OutOfMemoryError "Failed to allocate a 162 byte allocation with 44 free bytes and 44B until OOM" (recursive case)
12-04 16:38:56.699 11678-11814/org.eyeseetea.malariacare.hnqispull E/art: "AsyncTask #2" prio=5 tid=23 Runnable
12-04 16:38:56.699 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:   | group="main" sCount=0 dsCount=0 obj=0x12e0e3e0 self=0x9ef35c00
12-04 16:38:56.699 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:   | sysTid=11814 nice=10 cgrp=apps/bg_non_interactive sched=0/0 handle=0xafc53880
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:   | state=R schedstat=( 23006601332 4452028398 15510 ) utm=2113 stm=187 core=3 HZ=100
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:   | stack=0x9ebfc000-0x9ebfe000 stackSize=1036KB
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:   | held mutexes= "mutator lock"(shared held)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at java.util.LinkedHashMap.addNewEntry(LinkedHashMap.java:195)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at java.util.HashMap.put(HashMap.java:403)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapObject(UntypedObjectDeserializer.java:645)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:496)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at com.fasterxml.jackson.databind.deser.SettableAnyProperty.deserialize(SettableAnyProperty.java:138)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at com.fasterxml.jackson.databind.deser.SettableAnyProperty.deserializeAndSet(SettableAnyProperty.java:118)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1324)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:264)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2726)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at org.hisp.dhis.android.sdk.controllers.wrappers.AttributeValuesWrapper.deserialize(AttributeValuesWrapper.java:107)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at org.hisp.dhis.android.sdk.controllers.metadata.MetaDataController.getAttributeValuesDataFromServer(MetaDataController.java:788)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at org.hisp.dhis.android.sdk.controllers.metadata.MetaDataController.updateMetaDataItems(MetaDataController.java:654)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at org.hisp.dhis.android.sdk.controllers.metadata.MetaDataController.loadMetaData(MetaDataController.java:591)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at org.hisp.dhis.android.sdk.controllers.LoadingController.loadMetaData(LoadingController.java:150)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at org.hisp.dhis.android.sdk.controllers.DhisController.loadData(DhisController.java:109)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at org.hisp.dhis.android.sdk.controllers.DhisService$8.execute(DhisService.java:175)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at org.hisp.dhis.android.sdk.job.NetworkJob.inBackground(NetworkJob.java:50)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at org.hisp.dhis.android.sdk.job.NetworkJob.inBackground(NetworkJob.java:37)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at org.hisp.dhis.android.sdk.job.Job.doInBackground(Job.java:59)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at org.hisp.dhis.android.sdk.job.Job.doInBackground(Job.java:35)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at java.lang.Thread.run(Thread.java:818)
12-04 16:38:56.989 11678-11814/org.eyeseetea.malariacare.hnqispull E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                                                     Process: org.eyeseetea.malariacare.hnqispull, PID: 11678
                                                                                     java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                                         at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                                         at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                                         at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                         at java.lang.Thread.run(Thread.java:818)
                                                                                      Caused by: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack available

```

**Comment by ivanarrizabalaga** [comment]
There is an OOM error while loading attribute values from the server (before starting convertion).

The critical point in the stacktrace:

```
com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2726)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at org.hisp.dhis.android.sdk.controllers.wrappers.AttributeValuesWrapper.deserialize(AttributeValuesWrapper.java:107)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at org.hisp.dhis.android.sdk.controllers.metadata.MetaDataController.getAttributeValuesDataFromServer(MetaDataController.java:788)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at org.hisp.dhis.android.sdk.controllers.metadata.MetaDataController.updateMetaDataItems(MetaDataController.java:654)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at org.hisp.dhis.android.sdk.controllers.metadata.MetaDataController.loadMetaData(MetaDataController.java:591)
12-04 16:38:56.709 11678-11814/org.eyeseetea.malariacare.hnqispull E/art:     at org.hisp.dhis.android.sdk.controllers.LoadingController.loadMetaData(LoadingController
```

**Comment by ivanarrizabalaga** [comment]
The URL that it is being called while pulling attributes is:

https://hnqis.psi-mis.org/api/programs?fields=programStages[programStageSections[programStageDataElements[dataElement[id,attributeValues[*,attribute[*]]]]]]&paging=false&fields=%5B%3Aall%5D

**Comment by ivanarrizabalaga** [comment]
@ifoche Finally  solved!

It takes 14min. in my mobile but now it works.
I 've updated our **attributes_pull** branch of our sdk fork.

The process now shows the following times:

```
12-05 10:48:40.121 10749-10749/org.eyeseetea.malariacare.hnqispull D/.PullController: Starting PULL process...
12-05 10:48:40.261 10749-10943/org.eyeseetea.malariacare.hnqispull D/MetaDataController: loadMetaData
12-05 10:48:40.831 10749-10943/org.eyeseetea.malariacare.hnqispull D/MetaDataController: getAssignedProgramsDataFromServer
12-05 10:48:42.421 10749-10943/org.eyeseetea.malariacare.hnqispull D/MetaDataController: getProgramDataFromServer
12-05 10:48:49.241 10749-10943/org.eyeseetea.malariacare.hnqispull D/MetaDataController: getProgramDataFromServer
12-05 10:48:51.991 10749-10943/org.eyeseetea.malariacare.hnqispull D/MetaDataController: getProgramDataFromServer
12-05 10:48:56.611 10749-10943/org.eyeseetea.malariacare.hnqispull D/MetaDataController: getOptionSetDataFromServer
12-05 10:48:57.531 10749-10943/org.eyeseetea.malariacare.hnqispull D/MetaDataController: getAttributeValuesDataFromServer
12-05 10:48:57.531 10749-10943/org.eyeseetea.malariacare.hnqispull D/MetaDataController: getAttributeValuesDataFromServer page 1
12-05 10:49:13.461 10749-10943/org.eyeseetea.malariacare.hnqispull D/MetaDataController: getAttributeValuesDataFromServer page 2
12-05 10:49:24.291 10749-10943/org.eyeseetea.malariacare.hnqispull D/MetaDataController: getAttributeValuesDataFromServer page 3
12-05 10:49:31.831 10749-10943/org.eyeseetea.malariacare.hnqispull D/MetaDataController: getAttributeValuesDataFromServer page 4
12-05 10:49:59.211 10749-10943/org.eyeseetea.malariacare.hnqispull D/MetaDataController: getAttributeValuesDataFromServer page 5
12-05 10:50:25.151 10749-10943/org.eyeseetea.malariacare.hnqispull D/MetaDataController: getAttributeValuesDataFromServer page 6
12-05 10:50:48.081 10749-10943/org.eyeseetea.malariacare.hnqispull D/MetaDataController: getAttributeValuesDataFromServer page 7
12-05 10:51:28.431 10749-10943/org.eyeseetea.malariacare.hnqispull D/MetaDataController: getAttributeValuesDataFromServer page 8
12-05 10:51:35.481 10749-15050/org.eyeseetea.malariacare.hnqispull D/.PullController: Deleting app database...
12-05 10:51:35.511 10749-15050/org.eyeseetea.malariacare.hnqispull D/.PullController: Converting SDK into APP data
12-05 10:51:35.511 10749-15050/org.eyeseetea.malariacare.hnqispull I/.PullController: Converting programs, tabgroups and tabs...
12-05 10:51:35.611 10749-15050/org.eyeseetea.malariacare.hnqispull I/.PullController: Converting answers and options...
12-05 10:51:36.191 10749-15050/org.eyeseetea.malariacare.hnqispull I/.PullController: Converting organisationUnits...
12-05 10:51:36.211 10749-15050/org.eyeseetea.malariacare.hnqispull I/.PullController: Converting user...
12-05 10:51:36.221 10749-15050/org.eyeseetea.malariacare.hnqispull I/.PullController: Ordering questions and compositeScores...
12-05 10:54:31.201 10749-15050/org.eyeseetea.malariacare.hnqispull I/.PullController: Building questions,compositescores,headers...
12-05 11:00:25.101 10749-15050/org.eyeseetea.malariacare.hnqispull I/.PullController: Building relationships...
12-05 11:02:23.111 10749-15050/org.eyeseetea.malariacare.hnqispull I/.PullController: Building compositeScore relationships...
12-05 11:02:23.191 10749-15050/org.eyeseetea.malariacare.hnqispull I/.PullController: MetaData successfully converted...
12-05 11:02:23.191 10749-15050/org.eyeseetea.malariacare.hnqispull I/.PullController: Converting surveys and values for orgUnit: KE - HNQIS SF pilot test facility 2 | program: KE HNQIS HIV
12-05 11:02:23.561 10749-15050/org.eyeseetea.malariacare.hnqispull I/.PullController: Converting surveys and values for orgUnit: KE - HNQIS SF pilot test facility 2 | program: KE HNQIS Family Planning
12-05 11:02:24.011 10749-15050/org.eyeseetea.malariacare.hnqispull I/.PullController: Converting surveys and values for orgUnit: KE - HNQIS SF pilot test facility 1 | program: KE HNQIS IMCI
12-05 11:02:26.471 10749-15050/org.eyeseetea.malariacare.hnqispull I/.PullController: Converting surveys and values for orgUnit: KE - HNQIS SF pilot test facility 1 | program: KE HNQIS HIV
12-05 11:02:28.131 10749-15050/org.eyeseetea.malariacare.hnqispull I/.PullController: Converting surveys and values for orgUnit: KE - HNQIS SF pilot test facility 1 | program: KE HNQIS Family Planning
12-05 11:02:29.881 10749-15050/org.eyeseetea.malariacare.hnqispull D/.PullController: PULL process...OK

```

**Comment by ifoche** [comment]
@ivanarrizabalaga cool!!! Thanks for the efforts
